version: '3.7'

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=backstage
    ports:
      - '5432:5432'
    volumes:
      - backstage_data:/var/lib/postgresql/data

volumes:
  backstage_data:
