version: '3.9'

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - backstage_data:/var/lib/postgresql/data

volumes:
  backstage_data:
